stages:
- test
sast:
  stage: test
include:
- template: Security/SAST.gitlab-ci.yml
analyze:
  stage: test
  image: musicscience37/clang-ci
  script:
    - ln -s $(ls -1 /usr/bin/scan-build-* | head -n 1) /usr/bin/scan-build
    - make analyze
